import {
  LayoutDashboard,
  Settings,
  Users,
  Bot,
  Car,
  Book,
  Map,
  Ticket,
  Bell,
  Newspaper,
  Image as ImageIcon,
  Building2,
  Share2,
  Wallet,
  Crown,
  Store,
  PackageOpen,
  Megaphone,
  DollarSign,
  Scale,
  ArrowDownCircle,
  Receipt,
  MessageSquare,
  ShieldAlert,
  TrendingDown,
  PieChart,
  type LucideIcon,
} from 'lucide-react';

export type NavItem = { href: string; label: string; icon: LucideIcon };

// Menu trái admin. Mỗi mục (trừ /settings) ánh xạ 1 function trong rbac.ts
// (MENU_FUNCTION_BY_HREF). Thêm mục mới ở đây mà quên khai báo function -> test
// đồng bộ (rbac.test.ts) fail. Giữ ở module riêng (không icon-only trong layout)
// để test import được mà không kéo cả sidebar/matchMedia.
export const navItems: NavItem[] = [
  { href: '/dashboard', label: 'Tổng quan', icon: LayoutDashboard },
  { href: '/users', label: 'Người dùng', icon: Users },
  { href: '/drivers', label: 'Tài xế', icon: Car },
  { href: '/transport-companies', label: 'Đơn vị vận tải', icon: Building2 },
  { href: '/bookings', label: 'Chuyến đi', icon: Book },
  { href: '/referrals', label: 'Affiliate', icon: Share2 },
  { href: '/kol', label: 'KOL/KOC', icon: Crown },
  { href: '/agent', label: 'Đại lý đặt hộ', icon: Store },
  { href: '/agent-orders', label: 'Đơn đặt hộ', icon: PackageOpen },
  { href: '/withdrawals', label: 'Lệnh rút tiền', icon: Wallet },
  { href: '/finance', label: 'Tài chính', icon: DollarSign },
  { href: '/acquisition', label: 'Nguồn khách', icon: PieChart },
  { href: '/driver-cashflow', label: 'Dòng tiền tài xế', icon: ArrowDownCircle },
  { href: '/htx-reconciliation', label: 'Đối soát HTX', icon: Scale },
  { href: '/invoices', label: 'Hoá đơn', icon: Receipt },
  { href: '/master-data', label: 'Dữ liệu chung', icon: Map },
  { href: '/promotions', label: 'Khuyến mãi', icon: Ticket },
  { href: '/reports', label: 'Báo cáo', icon: Bot },
  { href: '/settings', label: 'Cài đặt', icon: Settings },
  { href: '/notifications', label: 'Thông báo', icon: Bell },
  { href: '/news', label: 'Tin tức', icon: Newspaper },
  { href: '/banners', label: 'Banner', icon: ImageIcon },
  { href: '/app-popups', label: 'Popup quảng cáo', icon: Megaphone },
  { href: '/feedback', label: 'Góp ý tài xế', icon: MessageSquare },
  { href: '/leakage-review', label: 'Nghi vấn gian lận', icon: ShieldAlert },
  { href: '/driver-cancel-review', label: 'Tỉ lệ huỷ tài xế', icon: TrendingDown },
];
